spring:
    datasource:
        username: sch_mgmt
        password: sch_mgmt
        url: jdbc:mysql://localhost:3306/sch_mgmt
        
    jpa:
        hibernate:
            ddl-auto: none
        show-sql: true
    
    sql:
        init:
            mode: never
            